# fly.toml app configuration file generated for js-h2c-test on 2023-10-26T20:01:10+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "js-h2c-test"
primary_region = "mad"

# [[services]]
#   protocol = "tcp"
#   internal_port = 8080
#   processes = ["app"]

#   [[services.ports]]
#     port = 443
#     handlers = ["tls", "http"]

[[services]]
  protocol = "tcp"
  internal_port = 8081
  processes = ["app"]

  [[services.ports]]
    port = 444
    handlers = ["tls"]
    tls_options = { "alpn" = ["h2"] }
